apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      env: test
  template:
    metadata:
      labels:
        env: test
    spec:
      containers:
      - name:  pipecd-test
        image: kubesahil221/demo-img:v2.0
        ports:
        - containerPort: 80

